mozilla/advocacy.mozilla.org

- 2016-host-organization-application/index.css
- 2016-host-organization-application/index.html
- get-involved/index.html
- index.css
- index.html
- open-web-fellows/index.html
Added new funder text
added node graphics to call for applications pages
updated menus
commented out mobile versions of sub menus
> updated text and menus and graphics

- 2016-host-organization-application/index.html
- get-involved/index.html
- index.html
- open-web-fellows/index.html
Removed all links to the application and fixed problem with Mobile view
> Remove 2016 application links

- components/encrypt-video.jsx
- pages/encrypt/default.jsx
- pages/encrypt/v2.jsx
- pages/encrypt/v3.jsx
> Hide theatre mode on click of overlay

- components/encrypt-video.jsx
- less/pages/encrypt/components.less
Appears in appropriate position on large screen, appears after closing video in mobile Safari.
> Modal fixes

- less/pages/encrypt/components.less
- less/pages/encrypt/index.less
- pages/encrypt/default.jsx
- pages/encrypt/index.jsx
- pages/encrypt/v2.jsx
> Red pen changes

- components/encrypt-logo.jsx
- pages/encrypt/default.jsx
- pages/encrypt/v2.jsx
- pages/encrypt/v3.jsx
- public/assets/footer-icon-medium.svg
and a style attribute. Darn hyphens.
> Fix medium icon in Chrome

- components/encrypt-signup.jsx
As per https://github.com/MozillaFoundation/encryption_campaign/issues/132#issuecomment-187119706
> Add Optimizely conversion tracking

- components/encrypt-video.jsx
> Make play button show up when out of theatre mode

- pages/encrypt/v2.jsx
Closes https://github.com/MozillaFoundation/encryption_campaign/issues/182
> Remove words from CTA

- lib/react-server-route.jsx
- pages/encrypt/index.jsx
No longer see unrendered code in Chrome
Closes https://github.com/MozillaFoundation/encryption_campaign/issues/215
> Fix initial rendering bug

- components/apply.jsx
- pages/open-web-fellows/fellows.jsx
- pages/open-web-fellows/info.jsx
- pages/open-web-fellows/overview.jsx
> OWF application submission closed

- components/encrypt-video.jsx
- less/pages/encrypt/components.less
- pages/encrypt/pageType.jsx
Fixes some of @mmmavis's previous comments and makes some CSS more specific.
> Syntax, fix a CSS bug

- data/encryptVideos.js
When the video at https://lit-mountain-52009.herokuapp.com/encrypt/hybrid/4 plays, this PR is ready to merge in.
> Correct Video4 video source

- data/encryptVideos.js
- pages/encrypt/social.jsx
Closes https://github.com/MozillaFoundation/encryption_campaign/issues/244
> Text changes

- package.json
- src/client.js
> Polyfill intl

- src/components/encrypt-signup.js
> Fix issue #210 - Set header form submission

- package.json
https://github.com/MozillaFoundation/mofo-devops-private/issues/32
> node 4.6.0

- src/pages/open-web-fellows/fellows2016.js
As per @vanessarhinesmith 
@ScottDowne 2 second R+?
> Remove a fellow's associated company

- src/components/fellows-header.js
- src/pages/open-web-fellows/fellows2015.js
- src/pages/open-web-fellows/fellows2016.js
- src/pages/open-web-fellows/overview.js
> Remove host application CFP

- src/pages/open-web-fellows/overview.js
Small change asked for by Vanessa
> Evergreen text on fellows host org page

- src/pages/open-web-fellows/fellows2017.js
Hi there, 
One of the fellows asked to update her site and bio after seeing our announcement go live, so, i've updated it in this PR. Also want to nod to #382 , which was just merged today, thank you @ScottDowne !
Looks like this when run locally, just a line of language update and a link:
Please merge when you can, and it's probably a good idea to keep this branch open in case there are other updates. Thank you so much!
> 2017 Fellows Bios Updata

- src/pages/open-web-fellows/fellows2017.js
Updated:
Merge when ready, thank you, @ScottDowne and sorry for another update!
> 2017 fellows updates 2

- less/pages/buyers-guide/item.less
Fixing this text cropping issue in Spanish https://screenshots.firefoxusercontent.com/images/f6a22772-b524-48c9-a77c-5e464afa0239.png
“Safety Review” string on the product page
> Fixing text cropping

- buyers-guide-locales/en-US/home.properties
- less/pages/buyers-guide/shared.less
- src/pages/buyers-guide/item.js
When you scroll down a product page, you'll now get a Donate CTA pop-up instead of the Email Subscription pop-up, like this...
Fixes https://github.com/mozilla/donate.mozilla.org/issues/1919
> Changed product page pop-up to Donate CTA

- less/pages/net-neutrality/index.less
- src/pages/net-neutrality/petition.js
**Changes**
* Popup appears after `750ms` instead of `1000ms` after scrolling
* Got rid of the blank scrollbars around the modal background
* Added slight animations to the popup when it appears
* Background fades in
* Popup does a little scale in
* This eases the jarring sensation of it appearing a bit
* Updated copy to match what we show on the Privacy not Included site
* Added a reasonable `max-width` for when the screen is wide
Should appear as...
cc @Pomax
> Donate modal styling updates

- less/components/footer.less
> Avoiding horizontal scroll

- src/pages/net-neutrality/call-now.js
> Add instruction footnote

- src/pages/net-neutrality/petition.js
As per @WillatMozFdn's request, as EOY is over.
Modal no longer appears at https://advocacy.mozilla.org/en-us/net-neutrality/petition/
> Remove NN scroll modal for now

- src/components/fellows-header.js
- src/components/open-web-fellows/apply.js
- src/pages/open-web-fellows/fellows2015.js
- src/pages/open-web-fellows/fellows2016.js
- src/pages/open-web-fellows/fellows2017.js
- src/pages/open-web-fellows/info.js
- src/pages/open-web-fellows/overview.js
- src/routes.js
Closes #493 
Doesn't go live till Tuesday Jan 16
> 2018 Host org application opening

- buyers-guide-locales/en-US/home.properties
- less/pages/buyers-guide/category.less
- less/pages/buyers-guide/home.less
- less/pages/buyers-guide/shared.less
- public/assets/buyers-guide/menu-burger.svg
- public/assets/buyers-guide/menu-close.svg
- src/components/buyers-guide/header.js
- src/components/buyers-guide/menu.js
- src/pages/buyers-guide/category.js
- src/pages/buyers-guide/home.js
- src/pages/buyers-guide/item.js
- src/pages/buyers-guide/why-we-made.js
- src/pages/net-neutrality/petition.js
> Adding new PNI nav

- less/pages/buyers-guide/category.less
- less/pages/buyers-guide/item.less
> PNI design qa fixes

- src/pages/open-web-fellows/fellows2015.js
- src/pages/open-web-fellows/fellows2016.js
- src/pages/open-web-fellows/fellows2017.js
- src/pages/open-web-fellows/overview.js
Closes #527 
* adds header button to apply to overview/ and redirects to foundation landing page for fellowship applicants
* adds footer with fellowship application redirect to all pages
> Open Fellows application redirect to foundation site

- src/pages/net-neutrality/call-page.js
- src/pages/net-neutrality/petition.js
changes based on https://docs.google.com/document/d/1y_xajlNM-x9u46rAcUMoHzvGPAwekJ9p7_EkpIbUxvs/edit#
> NN text changes

- src/pages/open-web-fellows/fellows2015.js
- src/pages/open-web-fellows/fellows2016.js
- src/pages/open-web-fellows/fellows2017.js
- src/pages/open-web-fellows/overview.js
This reverts commit 2e71ce36312d6a0f4fcfecfa69b15c49b6042604.
Applications are closed. https://github.com/mozilla/foundation.mozilla.org/issues/1573#issuecomment-393269517
> Revert "add open application redirect to foundation site (#528)"
